name : Docker Image Build

on:
  pull_request:
          branches: 
                  - main
                  - develop
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 22
                  cache: npm
            - name: NPM Install
              run: npm install
            
            - name: RUN LINT
              run: npm run lint
            
            - name: Run Unit Test
              run: npm test
            
            - name: Build Docker Image
              run: docker build -t cicd-app .
